#' calculates the proportion of time spent in each zone based on the whole time series passed in
#' from Analyis.R generated by Keni
#'
#' @param data interval table to generate time budget from
#' @param value name of column that contains all options (subzone)
#' @param options vector of options that value contains (bottom, middle, top)
#' @param n_opts number of options in vector (3)
#'
#' @return dataframe containing start, end and value as columns
#' @export
#'
#' @examples
#' columns <- c("t1","t2", "from_zone", "to_zone")
#' rows <- c("1616328905", "1616368409", NA, "bottom")
#' data <- data.frame(rbind(rows))
#' colnames(data) <- columns
#' get_time_budget_prop(data)
#'
get_time_budget_prop <- function(data,value,options,n_opts) {

  columns = c("interval","Bottom","Middle","Top")
  TBS = data.frame(matrix(nrow = 0, ncol = length(columns)))
  colnames(TBS) = columns

  if(all.equal(colnames(data),c("t1","t2","from_zone","to_zone"))){
    # store interval as minutes
    TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, to_zone=data$to_zone)
    Interval <- c(my_ymd_hms(as.POSIXct.numeric(as.numeric(utils::head(data,n=1)$t1),origin="1970-01-01")),my_ymd_hms(as.POSIXct.numeric(as.numeric(utils::tail(data,n=1)$t2),origin="1970-01-01")))

    TBbot<-sum(TBStag[which(TBStag$to_zone == "bottom"),]$t)/sum(TBStag$t)

    TBmid<-sum(TBStag[which(TBStag$to_zone == "middle"),]$t)/sum(TBStag$t)

    TBtop<-sum(TBStag[which(TBStag$to_zone == "top"),]$t)/sum(TBStag$t)

    TBS<-matrix(c(TBbot,TBmid,TBtop),ncol=3)

    return(data.frame(Interval[1],Interval[2],TBS))

  } else if(all.equal(colnames(data),c("t1","t2","zone"))){
    # store interval as minutes
    TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, zone=data$zone)

    Interval <- c(my_ymd_hms(as.POSIXct.numeric(as.numeric(utils::head(data,n=1)$t1),origin="1970-01-01")),my_ymd_hms(as.POSIXct.numeric(as.numeric(utils::tail(data,n=1)$t2),origin="1970-01-01")))

    TBbot<-sum(TBStag[which(TBStag$zone == "bottom"),]$t)/sum(TBStag$t)

    TBmid<-sum(TBStag[which(TBStag$zone == "middle"),]$t)/sum(TBStag$t)

    TBtop<-sum(TBStag[which(TBStag$zone == "top"),]$t)/sum(TBStag$t)

    TBS<-matrix(c(TBbot,TBmid,TBtop),ncol=3)

    return(data.frame(Interval[1],Interval[2],TBS))
  } else if(all.equal(colnames(data),c("t1","t2",value))){
    # store interval as minutes
    #TODO figure out how to generalize this
    TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, zone=data[[value]])

    Interval <- c(my_ymd_hms(as.POSIXct.numeric(as.numeric(utils::head(data,n=1)$t1),origin="1970-01-01")),my_ymd_hms(as.POSIXct.numeric(as.numeric(utils::tail(data,n=1)$t2),origin="1970-01-01")))
    for(i in 1:n_opts){
      TBopts[i] <- sum(TBStag[which(TBStag[[value]] == options[i]),]$t)/sum(TBStag$t)
    }


    TBS<-matrix(TBopts,ncol=n_opts)

    return(data.frame(Interval[1],Interval[2],TBS))
  } else {
    stop("this should not happen")
  }

}
